#-------------------------------
# General Site Settings
title: Surayyo
logo: logo.svg # You can add own logo.
description: Surayyo Consultante would help you to find your way in Germany!

#-------------------------------
# Author Settings
author:
  name: Surrayo Norkobilova
  image: 01.jpg
  say-hello: Hello, I’m <strong>Surrayo Norkobilova</strong>
  bio: I know how overwhelming moving to Germany can be—new language, tons of paperwork, and unfamiliar systems. I’ve been there too. That’s why I started this consultancy: to help foreigners like you navigate German bureaucracy, understand your options, and settle in confidently. With ten years of experience supporting internationals in Germany, I offer personalized, practical help—whether it's registering your address, applying for a visa, or just understanding how health insurance works. Let me help you save time, avoid stress, and feel at home.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
